name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Copy Static Assets
        run: |
          # Create necessary directories
          mkdir -p out/static/images
          mkdir -p out/static/blog

          # Copy images and blog assets
          cp -r public/static/images/* out/static/images/
          cp -r public/static/blog/* out/static/blog/

          # Debug output
          echo "Contents of out/static/images:"
          ls -la out/static/images/
          echo "Contents of out/static/blog:"
          ls -la out/static/blog/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: armanruet.github.io
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
